# Generated by Django 4.2.5 on 2024-03-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protagonists', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('trailer', models.URLField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('0', 'coming-up'), ('1', 'starting'), ('2', 'running'), ('3', '')], max_length=1)),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
