# Generated by Django 4.2.5 on 2024-03-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('coming-up', 'coming-up'), ('starting', 'starting'), ('running', 'running'), ('finished', 'finished')], max_length=9),
        ),
    ]
